let date = new Date();
console.log(date);
console.log(date.toDateString());
console.log(date.toString());
console.log(date.toDateString());
console.log(date.getDate());
console.log(date.getFullYear());
console.log(date.getMonth());
console.log(date.getTime());
console.log(date.getTimezoneOffset());
console.log(Date.now().toString());
